liquibase:
  change-log: classpath:/db/db.changelog.xml

server:
  port: 8080
  contextPath: /authentication

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect